---
title: "Herring FW9 Rebuild"
author: "Min-Yang Lee"
date: "6/30/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prices

Figure “herring_price_quantity_scatter.png” contains a scatterplot of real herring prices and landings, in 1000s of metric tons.    Data available after the Amendment 8 analysis is marked with triangles.  We have added an ordinary least squares regression line that describes this relationship.  We use this equation to predict the real annual prices corresponding to different harvest levels projected under the rebuilding plan.  We use this equation, rather than the one developed in Amendment 8. 

This equation is:
$$
price\_ per\_mt =  815.02 -   5.89 landings + \varepsilon
$$

# Rebuilding

To describe the projected revenues under the different rebuilding trajectories, we:

1.  Use the ABCs described in the various projections. When ABCs are low, we assume landings are equal to ABCs.  However, when ABCs are higher than higest observed US catch (124,100 mt in 1997), we set catch to this amount. 
1.  Construct predicted prices (in Real 2019 dollars) from the equation in the previous section. 
1.  Multiply price by landings to construct revenue.
1.  Discount by 7\% or 3\%. These are in Circular A-4 from 2003.

## Figures
We present a box plot of discounted revenues (for the ABC CR and Constant F) boxplot_discounted_rev.png.  This is discounted total revenue over the 2020-2032 time period (we can change this easily, as needed to exclude 2020 or 2021). The line inside the box 
represents the median outcome.  The upper and lower boxes edges of the boxes are the 25th and 75th percentile of total revenue.  The "whiskers" give some idea of the undertainty outside the 25th and 75th percentile.  Wider whiskers indicate more uncertainty. The dots given some idea about the uncertainty outside even those whiskers. 

The scenarios have similar upside  (the top whisker are similar for many scenarios). Some of the scenarios have quite different downside -- we infer this from the bottom whisker and the "outside values" (dots) that are below.  For example the ABC AR and Constant F AR have quite large bottom whiskers and outside values. 

There are two reason that the scenarios have similar upside.  First, some ABCs that are quite high; well outside the historcal range of catch. Because we set landings equal to the highest historical level, this limits total landings.  Second, prices decline when landings are high; this also limits revenue. 

We discount at 3\% and 7\% because OMB tells us to do so.




We also present a time series of the mean revenue and the 25th and 75th percentiles (in each year) -- not done yet



## Tables

Mean, std dev, and median of revenues for each alt.