---
title: "Am10_dataprep"
author: "Min-Yang Lee"
date: "2024-10-28"
output: html_document
---


1.  You must be able to see this folder ``nefscfile\BLAST\READ-SSB-Lee-MRIP-BLAST\data_folder\raw``. It contains the raw MRIP data that has been imported into Rds format. These were constructed with ``https://github.com/NEFSC/READ-SSB-MRIP-BLAST/R_code/data_extracting_processing/extraction/pull_in_MRIP.R``.  


```{r global_options, include=FALSE}
library("here")
library("data.table")
library("tidyverse")
library("knitr")
library("lubridate")
library("scales")
library("fredr")
library("kableExtra")
library("censusapi")
library("tigris")
library("mapview")
library("haven")
library("survey")
library("srvyr")

#turn off scientific notation
options(scipen=999)

#Handle single PSUs
options(survey.lonely.psu = "certainty")
options(tigris_use_cache = TRUE)

here::i_am("writing/Amendment10_data_prep.Rmd")

#############################################################################
#knitr options

knitr::opts_chunk$set(echo=FALSE, warning = FALSE, error = FALSE, message = FALSE, comment = FALSE, cache = FALSE, progress = TRUE, verbose = FALSE, 
											dpi = 600)
options(tinytex.verbose = TRUE)
# options(knitr.table.format = "latex")
#############################################################################


# RFA data
RFA_filepath<-file.path("//nefscdata","RFA_EO12866_Guidelines" ,"Ownership Data", "current data and metadata","affiliates_2024_06_01.Rdata")
BLAST_raw_filepath<-file.path("//nefscfile","BLAST" ,"READ-SSB-Lee-MRIP-BLAST", "data_folder","raw")
local_BLAST_folder<-file.path("V:","READ-SSB-Lee-MRIP-BLAST")
network_BLAST_folder<-file.path("//nefscfile","BLAST" ,"READ-SSB-Lee-MRIP-BLAST")


# run network
raw_mrip_folder<-file.path(network_BLAST_folder,"data_folder","raw")

# run local
raw_mrip_folder<-file.path(local_BLAST_folder,"data_folder","raw")

#############################################################################
# The census data that I'm using reports out 2022 Inflation adjusted dollars. Therefore, it makes sense to adjust everything to base year 2022.

deflate_by <- "year"
base_year = 2022 # base year for GDP deflator - Maximum = 2020, Minimum = 1947  - max(GDPDEF_quarterly$Year)


vintage_string<-Sys.Date()
vintage_string<-gsub("-","_",vintage_string)

```


```{r get_census, eval=TRUE}
# Pull in and tidy up some Census data on household income
income <- getCensus(
  name = "acs/acs5/subject",
  vintage = 2022,
  vars = c("S1901_C01_001E",  "S1901_C01_010E","S1901_C01_011E","S1901_C01_012E","S1901_C01_013E","S0101_C01_001E", "S0101_C02_028E","S0601_C01_001E","S0601_C01_022E"),
  region = "zip code tabulation area:*", 
  show_call=FALSE)

income<-income %>%
  rename ( households=S1901_C01_001E,
           household_inc_150_200pct =S1901_C01_010E,
           household_inc_200pct=S1901_C01_011E,
           household_median_inc=S1901_C01_012E, 
           household_mean_inc=S1901_C01_013E,
           total_population=S0101_C01_001E,
           population_pct_over60=S0101_C02_028E,
           total_population_s0601=S0601_C01_001E,
           pct_white_alone =S0601_C01_022E
           ) %>%
  mutate(obscured_median=case_when(household_median_inc<0 ~ 1, .default=0),
         obscured_mean=case_when(household_mean_inc<0 ~ 1, .default=0),
         obscured_population_pct_over60=case_when(population_pct_over60<0 ~ 1, .default=0),
         obscured_pct_white_alone=case_when(pct_white_alone<0 ~ 1, .default=0)
         )


# Read in the state-zcta correspondence file.
zcta_state<-read_delim("https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_county20_natl.txt", delim="|", guess_max=2000)

# Contract down to the fraction in each area.
zcta_state <- zcta_state %>%
  dplyr::filter(is.na(OID_ZCTA5_20)==FALSE) %>%
  group_by(OID_ZCTA5_20) %>%
  mutate(total_area=sum(AREALAND_PART)) %>%
  mutate(fraction=AREALAND_PART/total_area) %>%
  select(c(GEOID_ZCTA5_20, OID_ZCTA5_20,OID_COUNTY_20, GEOID_COUNTY_20, fraction))



# Pull in and tidy up some Census data on household income at the state level
county_income <- getCensus(
  name = "acs/acs5/subject",
  vintage = 2022,
  vars = c("S1901_C01_012E","S1901_C01_013E","S0101_C02_028E","S0601_C01_022E","S0101_C01_001E"),
  region = "county:*", 
  show_call=FALSE)

county_income<-county_income %>%
  rename (county_household_median_inc=S1901_C01_012E, 
          county_household_mean_inc=S1901_C01_013E,
          county_population_pct_over60=S0101_C02_028E,
          county_total_population=S0101_C01_001E,
          county_pct_white_alone =S0601_C01_022E
  ) %>%
  mutate(st_co=paste0(state,county))


# use county income to create an in imputed income based on county income
income_fill<-zcta_state %>%
  left_join(county_income, by=join_by(GEOID_COUNTY_20==st_co), relationship="many-to-one") %>%
  mutate(wmedian=fraction*county_household_median_inc,
         wmean=fraction*county_household_mean_inc,
         wpct60=fraction*county_population_pct_over60,
         wpct_wa=fraction*county_pct_white_alone
         ) %>%
  group_by(GEOID_ZCTA5_20, OID_ZCTA5_20) %>%
  summarise(imputed_household_median_income=sum(wmedian),
           imputed_household_mean_income=sum(wmean),
           imputed_fraction_over60=sum(wpct60),
           imputed_white_alone=sum(wpct_wa)
           ) %>%
  ungroup()

income<-income %>%
  left_join(income_fill, by=join_by(zip_code_tabulation_area==GEOID_ZCTA5_20), relationship="one-to-one")%>%
  mutate(household_median_inc=case_when(obscured_median==1 ~ imputed_household_median_income, .default=household_median_inc),
         household_mean_inc=case_when(obscured_mean==1 ~ imputed_household_mean_income, .default=household_mean_inc),
      population_pct_over60=case_when(obscured_population_pct_over60==1 ~ imputed_fraction_over60, .default=population_pct_over60),
      pct_white_alone=case_when(obscured_pct_white_alone==1 ~ imputed_white_alone, .default=pct_white_alone)
         ) %>%
  select(-c(imputed_household_mean_income,imputed_household_median_income))

summary(income)

# there is 1 zcta left without a median income. I'm just going to set it to mean income.
income<-income %>%
  mutate(household_median_inc=case_when(household_median_inc<0 ~ household_mean_inc, .default=household_median_inc))


saveRDS(income,file=here("data_folder", "main", paste0("income_",vintage_string,".Rds")))
saveRDS(zcta_state,file=here("data_folder", "main", paste0("zcta_state",vintage_string,".Rds")))
saveRDS(county_income,file=here("data_folder", "main", paste0("county_income",vintage_string,".Rds")))

```


```{r pull_zcta}
zcta<-zctas(cb=FALSE, year=2022)

saveRDS(zcta,file=here("data_folder", "main", paste0("zcta",vintage_string,".Rds")))



```




```{r get_MRIP, eval=FALSE}

specieslist<-c("stripedbass","blackseabass")

# This is a code to:
# Estimate the number of trips that targeted a particular species.
# I have previously read in all the sas7bdat files and converted them to Rds. This takes a little while.
# This has been verified by replicating the trips that Target Striped bass on the MRIP website

# Directed Trip query for trips by wave that have Primary Target=STRIPED BASS or Secondary Target=STRIPED BASS
# for 2023.

########################################SET UPS ################################
size_list<-list.files(path=raw_mrip_folder, pattern=glob2rx("size_2*.Rds"))
sizeb2_list<-list.files(path=raw_mrip_folder, pattern=glob2rx("size_b2_2*.Rds"))
catch_list<-list.files(path=raw_mrip_folder, pattern=glob2rx("catch_*.Rds"))
trip_list<-list.files(path=raw_mrip_folder, pattern=glob2rx("trip_*.Rds"))

year<-as.character(2020:2024)
year<-as.data.frame(year)
waves<-as.character(1:6)
waves<-as.data.frame(waves)

yearly<-merge(year,waves, all=TRUE)
readins<-paste0(yearly$year, yearly$waves)

readins<-as.list(readins)  


ma_site_allocation<-haven::read_dta(file.path(raw_mrip_folder,"ma_site_allocation.dta"))
names(ma_site_allocation) <- tolower(names(ma_site_allocation))


################################################################################
########################################SET UPS ################################



#Functions to read in Trips, Size, SizeB2, and catch Rds files

readin_trips <- function(waves) {
  in_dataset<-file.path(raw_mrip_folder,paste0("trip_",waves,".Rds"))
  
  if(file.exists(in_dataset)==TRUE){
    output<-readRDS(in_dataset)
    return(output)
  }
}


readin_size <- function(waves) {
  in_dataset<-file.path(raw_mrip_folder,paste0("size_",waves,".Rds"))
  
  if(file.exists(in_dataset)==TRUE){
    output<-readRDS(in_dataset)
    return(output)
  }
}


readin_catch <- function(waves) {
  in_dataset<-file.path(raw_mrip_folder,paste0("catch_",waves,".Rds"))
  
  if(file.exists(in_dataset)==TRUE){
    output<-readRDS(in_dataset)
    return(output)
  }
}

readin_size_b2 <- function(waves) {
  in_dataset<-file.path(raw_mrip_folder,paste0("size_b2_",waves,".Rds"))
  
  if(file.exists(in_dataset)==TRUE){
    output<-readRDS(in_dataset)
    return(output)
  }
}









################################################################################
################################################################################
######READ in Trip Dataset####################

################################################################################
# Trips
################################################################################


# Process Trip 

# Add a directedtrip (dtrip)= 1 column and make all the column names lowercase
# convert contents of prim1_common and prim2_common to lower case and remove white space
# Pad out st and cnty.  create stco.


trip_dataset<-lapply(readins,readin_trips)
trip_dataset<-rbindlist(trip_dataset, fill=TRUE)











trip_dataset<-trip_dataset %>%
  mutate(dtrip=1) %>%
  rename_all(tolower)%>%
  mutate(prim1_common=str_to_lower(prim1_common),
         prim2_common=str_to_lower(prim2_common)
         )%>%
  mutate(prim1_common=str_replace_all(prim1_common, pattern=" ", ""),
         prim2_common=str_replace_all(prim2_common, pattern=" ", "")
         ) %>%
  mutate(st=str_pad(st,2,pad="0"),
         cnty=str_pad(cnty,3,pad="0"),
         stco=paste0(st,cnty))


trip_dataset<-trip_dataset %>%
  left_join(ma_site_allocation, by=join_by(intsite==site_id))
rows_of_trip<-nrow(trip_dataset)

trip_dataset<-trip_dataset %>%
  mutate(mode=ifelse(mode_fx==4,"FH",ifelse(mode_fx==5,"FH","PR"))
)



# Classify rows in "trip" that are in my domain. At the end of this code, I need the same number of rows as the original trip dataset

# rows_of_trip<-nrow(trip_dataset)) 
#   group_by(year, wave, strat_id, psu_id, id_code)%>%

#create a categorical for whether the row caught or targeted species in specieslist

trip_dataset<-trip_dataset %>%
  mutate(targeted=case_when(prim1_common %in% specieslist ~1, .default=0)
  ) %>%
  mutate(targeted=case_when(prim2_common %in% specieslist ~1, .default=targeted)
)


# sum those variables, so they are constant within each year, wave, strat_id, psu_id, id_code. Pick of the first row.
trip_dataset<-trip_dataset %>%
  group_by(year, wave, strat_id, psu_id, id_code)%>%
  mutate(targeted=sum(targeted)) %>%
  slice_head(n=1) %>%
  ungroup()

# Classify as in my domain if caught or targeted
trip_dataset<-trip_dataset %>%
 mutate(dom_id=case_when(targeted>=1 ~ 1, .default=0) 
         )

# # You might want to adjust this by filtering: just new England or just ME, MA, NH.
# Be careful where you put this piece of code
# trip_dataset$dom_id[!trip_dataset$sub_reg %in% c(4)]<-2
# trip_dataset$dom_id[!trip_dataset$st %in% c(23,33,25)]<-2
# # Use the ma_site_allocation to classify intercept sites into GOM and not?
# trip_dataset$dom_id[!trip_dataset$stock_region_calc %in% c("NORTH")]<-2





# Drop protest st_res fips codes
# trip_dataset<-trip_dataset %>%
#   dplyr::filter(st_res<99)
 
# Targeting 
# srvyr data prep

 
tidy_trips_in<-trip_dataset %>%
  as_survey_design(id=psu_id, weights=wp_int, strata=strat_id, nest=TRUE, fpc=NULL)

target_totals_stco<-tidy_trips_in %>%
   dplyr::filter(dom_id==1) %>%
   group_by(year, wave,stco ) %>%
   summarise(dtrip=round(survey_total(dtrip))
)

 target_totals_stco$target<-paste(specieslist, collapse = "_")
 
 
target_totals_zip<-tidy_trips_in %>%
  dplyr::filter(dom_id==1) %>%
  group_by(st_res, zip ) %>%
  summarise(dtrip=round(survey_total(dtrip))
  )

target_totals_zip$target<-paste(specieslist, collapse = "_")



saveRDS(target_totals_stco,file=here("data_folder", "main", paste0("targeted_stco_",vintage_string,".Rds")))
saveRDS(target_totals_zip,file=here("data_folder", "main", paste0("targeted_zip_",vintage_string,".Rds")))


```

